### ISSUE TITLE
Bug: Deleted text in AdditionalInfoWidget is put on the Redo stack

### ISSUE THREAD

**Issue by kevinhorst** [MaxFleur/LightCombatManager#21]
How to reproduce:

1. create new combat with any name and empty additional information
2. add additional information, e.g "testbug"
3. Focus out of the widget
4. Focus into the widget again and mark the additional information
5. Delete additional information
5.(a) Delete the additional information by pressing the return or delete key, or using the menu
5(b): Delete every chacater by pressing the return key without marking first
6. Enter new additional informationand save
7. When going back, the old info "testbug" is still present, without ever being saved
8. It is not present when going forward, the two states have diverged

Tested on: Windows 10

**Comment by MaxFleur** [comment]
Can confirm this also for Linux. Good thing to fixfor 1.11.1.

**Comment by MaxFleur** [comment]
Fixed with commit 40b227f.
